Basic
tigran-edu/Large-Prime-Numbers pull request #1
Opened 2024-01-14 17:38 UTC by tigran-edu

2024-01-19 11:43 UTC, DimaTrushin reviewed
Обрати внимание, что я не делал комментарии в повторяющихся местах. Я ожидаю, что ты по аналогии исправишь все похожие места.

Добавь clang-format. А то у тебя очень много страшных вертикальных пробелов.

Часть алгоритмов видимо удобнее завернуть в функторы.

Обрати внимание на передачу данных by value. Следи за тем, чтобы у тебя не было лишнего копирования.

2024-01-19 11:43 UTC, DimaTrushin commented on CMakeLists.txt
> +set (DEBUG_INFO_FLAGS "-g -gdwarf-4")
Никогда не делай компиляторо зависимые флаги глобально. Сделай проверку на компилятор и внутри этой проверки, если компилятор тот который нужный, уже вводишь этот макрос.

2024-01-19 11:43 UTC, DimaTrushin commented on CMakeLists.txt
> +set (CMAKE_CXX_FLAGS_RELWITHDEBINFO      "${CMAKE_CXX_FLAGS_RELWITHDEBINFO} -O3 ${DEBUG_INFO_FLAGS} ${CMAKE_CXX_FLAGS_ADD}")
Никогда не подключай компиляторо зависимые флаги напрямую без проерки на компилятор. Оберни в проверку  вида if(gcc) или if(clang) и только внутри нее делай такие присваивания. Иначе клиент не сможет у себя даже собрать твое решение.

2024-01-19 11:43 UTC, DimaTrushin commented on CMakeLists.txt
> +include(cmake/sanitize.cmake)
Санитайзеры доступны только на gcc и clang под Linux. Может быть под Mac, я не в курсе. Под виндой они точно не доступны. Так что этот инклуд просто так делать нельзя без проверки на OS и на компилятор.

2024-01-19 11:43 UTC, DimaTrushin commented on CMakeLists.txt
> +add_subdirectory(programs)
Кирпичи. В конце каждого файла пустая строка, чтобы гит не выдавал ошибки твоему клиенту, когда он будет клонить.

2024-01-19 11:43 UTC, DimaTrushin commented on cmake/glob_sources.cmake
> +    add_glob(${prefix}_headers ${common_path}/*.h)
А зачем тебе глобально хранить в переменной h файлы?

2024-01-19 11:43 UTC, DimaTrushin commented on programs/main.cpp
> +using boost::multiprecision::cpp_int;
Старайся юзинги помещать как можно ближе к использующему коду. Например этот можно перенести внутрь main.

2024-01-19 11:43 UTC, DimaTrushin commented on src/CMakeLists.txt
> +add_library(lpn_core ${lpn_core_headers} ${lpn_core_sources})
Тут не надо включать h файлы, убери lpn_core_headers. Дело в том что add_library должна знать source файлы из которых собрать библиотеку. Заголовочные ей не нужны, потому ты просто лишние файлы будешь компилировать.

2024-01-19 11:43 UTC, DimaTrushin commented on src/basic.h
> +cpp_int gcd(cpp_int a, cpp_int b);
Уверен, что ты хочешь принимать объекты для длинки by value? Учитывая, что это не шаблоны и тела функций объявлены в cpp файлах, то нет шанса на inline функции при вызове. Потому все параметры функции будут переданы by value, то есть будут скопированы. Это может быть дорого. Содержательный вариант сделать const cpp_int&.

2024-01-19 11:43 UTC, DimaTrushin commented on src/basic.cpp
> +std::vector<cpp_int> primes = {2, 3, 5, 7, 11, 13};
- Если объявляешь какие-либо:
1) переменные
2) классы
3) функции
обязательно оборачивай их в anonymous namespace иначе это черевато проблемами с линкером.
- Кроме того, у тебя конечное и очень маленькое моженство. Непонятно почему не std::array? И почему не constexpr.

2024-01-19 11:43 UTC, DimaTrushin commented on src/basic.cpp
> +bool PseudoprimeTest(cpp_int p)
1) Очень плохо, что эта функция неявно использует глобальные данные. Если уж тебе нужны данные для функции, то надо завернуть в класс и сделать данные локальными данными класса. Тогда ты можешь настраивать эти данные при построении instance класса. Например
```cpp
class PseudoprimeTester {
public:
  // конструкторы и методы по настройке класса
  bool test(const cpp_int& p) const;
private:
  std::vector<cpp_int> primes_ = getDefaultList();
};
```
2) Другой вариант, надо явно этой функции передавать список простых. Это избавляет от необходимости вводить тут глобальную константу в виде primes. По сути у тебя константы будут контролироваться только в том коде, который вызывает функцию. Для начала в тестах.

2024-01-19 11:43 UTC, DimaTrushin commented on src/basic.cpp
> +    while (div * div <= a)
Любопытно, что будет быстрее извлечь разово корень из a и привести его к целому в длинке или каждый раз в цикле считать квадрат. Было бы интересно это замерить.

2024-01-19 11:43 UTC, DimaTrushin commented on src/basic.cpp
> +        if (a % div == 0)
Очень криво написано. У тебя лишний раз квадрат будет считаться в цикле. Тут ты мог сделать не if, а while до тех пор, пока делится и после него уже увеличить div.

2024-01-19 11:43 UTC, DimaTrushin commented on src/basic.cpp
> +            div++;
Этот код можно ускорить в разы. Ты можешь в начале до цикла проверить div = 2. Потом перед вызовом цикла сделать div = 3. И потом идти div += 2. Это позволяет ускориться в 2 раза.

2024-01-19 11:43 UTC, DimaTrushin commented on src/basic.cpp
> +        a = tmp;
Можно писать в одну строчку
```cpp
a = std::exchange(b, a % b);
```

2024-01-19 11:43 UTC, DimaTrushin commented on src/basic.cpp
> +
У тебя нет clang-format. Вот тут слишком большие пробелмы. У меня такое ощущение всегда, что я читаю пустые строки вместо кода.

2024-01-19 11:43 UTC, DimaTrushin commented on src/factorization.h
> +using boost::multiprecision::cpp_int;
1) У тебя этот using уже есть в basics.
2) Лучше сделать 
```cpp
using cpp_int = boost::multiprecision::cpp_int;
```
Или вообще сделать другое имя типа long_int, чтобы не зависить от имени бустовского и имени.

2024-01-19 11:43 UTC, DimaTrushin commented on src/factorization.cpp
> +                    while (n % g == 0)
1) У тебя 6 вложенных scope! Даже в ядре Linux запрещено делать больше 3. Это требует рефактора.
2) У тебя три вложенных цикла подряд! Ты тестировал, что так быстрее работает, чем если разбить на нормальные вызовы функций или просто написал спагетти-код?

Это требует рефактора.

2024-01-19 11:43 UTC, DimaTrushin commented on src/factorization.cpp
> +            if (terms % 10 == 0 || j + 1 == range)
Что за магические константы и странные проверки?
Вот как понять, что тут проверяется? Почему нельзя создать функция вида is_something_true(terms, j, range)?

2024-01-19 11:43 UTC, DimaTrushin commented on src/factorization.cpp
> +        for (cpp_int j = 0; j < range; ++j)
Плохое имя для переменной. Так как оно типа cpp_int, то это явно значит, что она участвует не как индекс в алгоритме, а значит несет какой-то смысл.

2024-01-19 11:43 UTC, DimaTrushin commented on src/factorization.cpp
> +    cpp_int terms = 0;
Это норм, что тут такие магические константы?

2024-01-21 07:37 UTC, tigran-edu commented on src/basic.cpp
> +
у меня есть clang-format, даже clang-tidy есть. Это после рефактора

2024-01-21 08:36 UTC, tigran-edu commented on cmake/glob_sources.cmake
> +    add_glob(${prefix}_headers ${common_path}/*.h)
Для универсальности сmake, думал изначально писать некоторый код в h файлах.

2024-01-21 09:10 UTC, tigran-edu commented on CMakeLists.txt
> +include(cmake/sanitize.cmake)
кажется мне тут никакие санитайзеры не понадобятся, поэтому даже не стоит делать include

2024-01-21 10:29 UTC, tigran-edu commented on src/basic.cpp
> +std::vector<cpp_int> primes = {2, 3, 5, 7, 11, 13};
constexpr с cpp_int не возможен, там в кишках не компайл там штука используется

2024-01-21 13:30 UTC, tigran-edu commented on src/factorization.cpp
> +        for (cpp_int j = 0; j < range; ++j)
это индекс, изменил на size_t

2024-01-21 19:34 UTC, tigran-edu commented on src/basic.h
> +cpp_int gcd(cpp_int a, cpp_int b);
В большинстве случаев у меня внутри функции параметры изменяются, так что нельзя их передавать бу ссылка, но где возможно - исправил.

2024-03-29 11:24 UTC, DimaTrushin requested changes
Обрати внимание, что я не повторял замечания. Если одна и та же ошибка всречалась несколько раз, я комментировал лишь единожды. Потому я ожидаю, что ты поправишь все аналогичные замечания всюду.

2024-03-29 11:24 UTC, DimaTrushin commented on .github/workflows/test.yml
неплохо.

2024-03-29 11:24 UTC, DimaTrushin commented on CMakeLists.txt
> +if (CMAKE_CXX_COMPILER_ID MATCHES "Clang" OR CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
а почему одно matches, а другое strequal?

2024-03-29 11:24 UTC, DimaTrushin commented on Dockerfile
Мне бы понять как это работает и как это с проектом сопряжено.

2024-03-29 11:24 UTC, DimaTrushin commented on readme.md
Вот сюда стоит добавить инструкцию по сборке. Я вижу у тебя докер файл. Означает ли это, что я должен что-то дополнительно проделать, чтобы все это запустилось?

2024-03-29 11:24 UTC, DimaTrushin commented on programs/main.cpp
> +    auto start = std::chrono::high_resolution_clock::now();
Сделай нормальный класс таймера, который внутри себя делает всю работу с chrono. И возвращай из него время в заданных единицах измерения вроде getSeconds или getMiliseconds и так далее. И еще можно добавить якоря, чтобы они автоматически в лог писали при разрушении.

2024-03-29 11:24 UTC, DimaTrushin commented on programs/main.cpp
> +    std::cout << duration.count() / 1e6 << std::endl;
1e6 -- магическая константа.

2024-03-29 11:24 UTC, DimaTrushin commented on src/basic.hpp
> +using Factor = std::unordered_map<long_int, size_t>;
1) я бы вынес эти штуки в отдельный хедер. Потому что я так понимаю они у тебя глобальные, но тогда получается все кто просто хотят знать этот псевдоним в придачу получают и все содержимое этого файла.
2) Плохое название для второго юзинга. Тут можно было бы FactorSet написать, ну или хотя бы Factors, ибо явно же у тебя тут контейнер. При этом слово Set даже не обманывает пользователя, так как это деревянная структура.

2024-03-29 11:24 UTC, DimaTrushin commented on src/basic.hpp
> +#include <iostream>
Этот хедер нигде не используется. Не включай лишние хедеры.

2024-03-29 11:24 UTC, DimaTrushin commented on src/basic.hpp
> +bool PseudoPrimeTest(const long_int & p, const std::array<long_int, N> & primes)
1) Плохая идея принимать конкретный контейнер. Тогда ты привязан к тому, чтобы создавать именно этот контейнер. И если ты передашь другой контейнер, который может кастануться к этому, то это создание временного контейнера. Например такое может быть, если ты std::initializer_list передашь. Ну и мало какие еще ситуации бывают.
2) Как вариант можно передавать либо итераторы, либо view на контейнеры вроде std::span, если у тебя c++20.
3) Кроме того, раз функция все равно шаблонная, что мешало принять контейнер как шаблонный аргумент и сделать сигнатуру
```cpp
template<class Container>
bool PseudoPrimeTest(const long_int& p, const Container& primes);
```
4) Плохое название функции. Оно не начинается с глагола, потому не понятно, что именно она делает. В сочетании с тем, что возвращаемое значение bool, то надо еще догадаться, что значит результат. Лучше в таких случаях делать enum class Status и возвращать статус с нормальным именем типа Status::Prime, Status::Composite, Status::Pseudoprime, Status::StrongPseudprime и т.д.

2024-03-29 11:24 UTC, DimaTrushin commented on src/basic.hpp
> +                return true;
Вот это уже четвертый вложенный scope, даже в ядре Linux запрещено больше 3.

2024-03-29 11:24 UTC, DimaTrushin commented on src/basic.hpp
> +        }
Вот это отдельная работа по нахождению разложения с отфакторизованной двойкой. Можно было это оформить в виде подфункции.

2024-03-29 11:24 UTC, DimaTrushin commented on src/basic.hpp
> +class LegendreSymbol
Не хочешь еще Jacobi Symbol добавить. Он совпадает с лежандром, когда лежандр определен, но при этом считается быстрее.

2024-03-29 11:24 UTC, DimaTrushin commented on src/basic.hpp
> +    static void PullTwos(long_int & n, int & legendre, const long_int & p);
Если у тебя есть входные и выходные аргументы, то обычно следуют следующим правилам:
1) все входные передаются by value или by const reference.
2) все выходные передаются by pointer
3) все входные идут до всех выходных, выходные идут в самом конце.

2024-03-29 11:24 UTC, DimaTrushin commented on src/basic.hpp
> +bool BasicIsPrime(const long_int & a);
начинай функции с глагола

2024-03-29 11:24 UTC, DimaTrushin commented on src/basic.hpp
> +Factor BasicFactorization(long_int a);
FactorizeBasic

2024-03-29 11:24 UTC, DimaTrushin commented on src/basic.cpp
> +    for (auto & [key, value] : second)
я бы тут был более специфичным и написал const auto&

2024-03-29 11:24 UTC, DimaTrushin commented on src/basic.cpp
> +size_t FullDiv(long_int & a, const long_int & b)
Плохое название. Не понятно из названия, что вообще тут происходит и что эта функция делает.

2024-03-29 11:24 UTC, DimaTrushin commented on src/basic.cpp
> +    while (b != 0)
А у тебя отрицательные b вообще не обрабатываются? Надо тогда хотя бы assert поставить, чтобы проверять, что ты случайно отрицательное число не подставил.

2024-03-29 11:24 UTC, DimaTrushin commented on src/basic.cpp
> +size_t FullDivFast(long_int & a, const long_int & b, size_t i)
Функция с такой сигнатурой является вспомогательной. Для пользователя нет смысла менять последний аргумент с дефолтного значения. Потому лучшье эту функцию сделать приватной и вспомогательной, а для полного выделения множителя сделать функцию с двумя первыми аргументами, чтобы не было соблазна снаружи вызывать ее неправильно.

2024-03-29 11:24 UTC, DimaTrushin commented on src/basic.cpp
> +    PullTwos(n, legendre, p);
А не лучше ли было бы явно возвращать новое значение символа
```cpp
legendre = PullTwos(n, legendre, p);
```
? И название функции не понятно что значит.

2024-03-29 11:24 UTC, DimaTrushin commented on src/basic.cpp
> +    }
А почему нельзя было через быстрое выделение степени выделить степень, а потом проверить ее на четность через deg & 1?

2024-03-29 11:24 UTC, DimaTrushin commented on src/basic.cpp
> +    if (auto counter = FullDiv(a, 2); counter > 0)
А почему не используется fast версия?

2024-03-29 11:24 UTC, DimaTrushin commented on src/basic.cpp
> +        div++;
можно делать +=2 и бежать только по нечетным.

2024-03-29 11:24 UTC, DimaTrushin commented on src/basic.cpp
> +    while (div * div <= a)
не шустрее было бы корень один раз посчитать и правильно округлить?

2024-03-29 11:24 UTC, DimaTrushin commented on src/gaussian.hpp
> +        Bitset(size_t n, size_t m) : participants(n), mask(m) {}
Зачем конструктора для структуры?

2024-03-29 11:24 UTC, DimaTrushin commented on src/gaussian.hpp
> +        void operator^=(Bitset & bitset)
врзвращай Bitset& чтобы можно было чейнить операции.

2024-03-29 11:24 UTC, DimaTrushin commented on src/gaussian.cpp
> +    : n_(factors.size()), m_(primes.size()), factors_(factors)
Мне всегда не нравится, когда происходит копирование контейнеров. Например у тебя тут происходит копирование в строчке
```cpp
factors_(factors)
```
Просто если ты передашь временный объект в качестве этого аргумента, то ты сделаешь лишнюю копию от временного контейнера. Ну и вообще сложно представить ситуацию, когда тебе надо factors снаружи держать и постоянно давать копию другому объекту. Тогда надо либо съесть эти данные и принимать std::vector<Factors>&& чтобы мувнуть данные. Либо если factors хранится снаружи гарантированно, то можно принимать итераторы или std::span.

2024-03-29 11:24 UTC, DimaTrushin commented on src/gaussian.cpp
> +    }
Можно обернуть это в статический метод построения matrix и потом вызвать этот метод в списке инициализации.
```cpp
static std::vector<Bitset> createMatrix(...);
// и в конструкторе:
matrix_(createMatrix(...))
```

2024-03-29 11:24 UTC, DimaTrushin commented on src/gaussian.cpp
> +        Add(pos, i);
Нарушение уровня абстракции. У тебя здесь идет вызов функции выполняющей сложную работу, а выше идет сырой цикл, выполняющий низкоуровневую работу. У тебя код не на одном уровне абстракции написан.

2024-03-29 11:24 UTC, DimaTrushin commented on src/gaussian.cpp
> +void GaussianBasic::Print()
1) Лучше вместо метода print перегружать оператор operator<< для вывода в потоки. Тогда можно их друг через друга выражать и так очень легко писать всякие методы вывода и сереализации. Но тут и так пойдет пока.
2) Что сразу бросается в глаза, почему метод не const? Почему метод для печати на экран может изменить объект?

2024-03-29 11:24 UTC, DimaTrushin commented on src/qs.hpp
> +using boost::multiprecision::cpp_bin_float_100;
Вот тут не понятно. Это namespace или имя типа. И где это используется? Почему ты раскрываешь это имя глобально?

2024-03-29 11:24 UTC, DimaTrushin commented on src/qs.hpp
> +    static long_int CheckResults(SieveResult & result, const GaussianBasic::Bitset & solution, const long_int & n);
Внутри класса нет необходимости обращаться к длинным именам. Сделай в начале класса в приватной зоне следующий using
```cpp
using Bitset = GaussianBasic::Bitset;
```
Это повысит читаемость кода.

2024-03-29 11:24 UTC, DimaTrushin commented on src/qs.hpp
> +    static long_int CheckResults(SieveResult & result, const GaussianBasic::Bitset & solution, const long_int & n);
Очень странно, что у тебя функция что-то возвращает и еще у нее есть аргумент с названием result. Это странно.

2024-03-29 11:24 UTC, DimaTrushin commented on src/qs.hpp
> +        {
Почему внезапно имплементации в h файле?

2024-03-29 11:24 UTC, DimaTrushin commented on src/qs.hpp
> +        explicit Config(const long_int & n)
Конструктор у структуры? Это значит у тебя есть инвариант на данные? Если есть, то почему тогда данные открыты. Если нет, то зачем конструктор? Если конструктор нужен для построения удобного объекта, то вместо этого можно воспользоваться named constructor idiom, когда ты с помощью статического метода строишь новую структуру.

2024-03-29 11:24 UTC, DimaTrushin commented on src/qs.hpp
> +        void ComputeCloseness(const long_int & max_prime) { closeness = target - t * log10(float(max_prime)); }
Очень странный метод. Метод на структуре, который ничего не возвращает. То есть он меняет структуру. Столько вопросов и так мало ответов...

2024-03-29 11:24 UTC, DimaTrushin commented on src/qs.hpp
> +            while (primes.size() <= factor_size)
Раз ты знаешь, что у тебя размер должен остановиться на factor_size, то почему не сделать reserve для primes в самом начале, чтобы не было аллокаций?

2024-03-29 11:24 UTC, DimaTrushin commented on src/qs.hpp
> +            size_t p = 3;
Что мешало завести эту переменную внутри цикла? Она вне цикла не используется.

2024-03-29 11:24 UTC, DimaTrushin commented on src/qs.hpp
> +                p++;
```cpp
p += 2;
```

2024-03-29 11:24 UTC, DimaTrushin commented on src/qs.hpp
> +        static size_t Size(const long_int & n) { return n.str().size(); }
Метод str() строит строку в этом месте? Не будет ли это дорого? Нет другой альтернативы посчитать количество символов?

2024-03-29 11:24 UTC, DimaTrushin commented on src/qs.hpp
> +        static size_t Size(const long_int & n) { return n.str().size(); }
Зачем этот метод спрятан в структуре? Это больше похоже на общий метод для работы с long_int.

2024-03-29 11:24 UTC, DimaTrushin commented on src/qs.hpp
> +            ComputeCloseness(primes.back());
Опять нарушение уровня абстракции. Тут высокоуровневая функция, а перед этим сырой цикл.

2024-03-29 11:24 UTC, DimaTrushin commented on src/qs.hpp
> +    static std::optional<Factor> IsDecomposed(Config & cf, size_t i, const long_int & n);
Плохое название. Is подразумевает, что результат bool, а у тебя результат optional. Это не is, это TryToDecompose

2024-03-29 11:24 UTC, DimaTrushin commented on src/qs.hpp
> +    static void CacheSaveFill(size_t i, size_t j, size_t p, std::vector<float> & logs);
Вот как из названия понять, что этот метод делает? Это три глагола в названии или что?

2024-03-29 11:24 UTC, DimaTrushin commented on src/qs.hpp
> +    static long_int F(const long_int & r, const long_int & n, size_t i);
отличное название метода.

2024-03-29 11:24 UTC, DimaTrushin commented on src/qs.cpp
> +    for (auto & sol : solutions)
Нарушение уровня абстракции.

2024-03-29 11:24 UTC, DimaTrushin commented on src/qs.cpp
> +            long_int check = CheckResults(result, sol, n);
Плохое название метода. Что за check возвращает этот метод? Что тут за ерунда?

2024-03-29 11:24 UTC, DimaTrushin commented on src/qs.cpp
> +        if (sol.mask.none())
Когда ты пишешь код вида sol.mask.none() это значит, что у тебя не хватает вспомогательной функции которая принимает sol.mask, а уже внутри себя обращается к mask.none(). Ты залазишь в кишки кишков. Это нарушение уровня доступа.

2024-03-29 11:24 UTC, DimaTrushin commented on src/qs.cpp
> +long_int QuadraticSieve::CheckResults(SieveResult & result, const GaussianBasic::Bitset & solution, const long_int & n)
Почему метод check принимает что-то по не константной ссылке?

2024-03-29 11:24 UTC, DimaTrushin commented on src/qs.cpp
> +{
Глобально логика кода выглядит так
```cpp
long_int x = createX(...);
long_int y = createY(...);
return gcd(abs(x - y), n);
```
Возникает вопрос, почему не написано так? Неужели это нельзя разбить в нормальные подфункции с нормальными именами?

2024-03-29 11:24 UTC, DimaTrushin commented on src/qs.cpp
> +    return lpn::gcd<long_int>(boost::multiprecision::abs(x - y), n);
Заведи псевдоним для этого длинного обращения.

2024-03-29 11:24 UTC, DimaTrushin commented on src/qs.cpp
> +            p.str());
Это ошибка программиста если эта функция так вызвана? Если да, то почему не assert?
И еще, раз ты кидаешь исключения, надо main правильно заворачивать
```cpp
#include "Tests.h"
#include "Except.h"

int main() {
  try {
    proj::run_all_tests();
  } catch(...) {
    except::react();
  }
  return 0;
}
Except.h
namespace except {
void react();
}
Except.cpp
#include "Except.h"

namespace except {
void react() {
  try {
    throw;
  } catch(std::exception& e) {
    // обрабатываешь известные исключения
  } catch(...) {
    // обрабатываешь незивестные исключения
  }
}
}
```

2024-03-29 11:24 UTC, DimaTrushin commented on src/qs.cpp
> +    while (true)
Блять...

2024-03-29 11:24 UTC, DimaTrushin commented on src/qs.cpp
> +    boost::random::mt19937 gen{42};
Так у тебя получается не случайное поведение у функции. Каждый вызов на одном и том же входе будет давать один и тот же ответ. Лучше сделать эту переменную статической, чтобы хотя бы была возвожность увидеть разницу между разными вызовами. Инициализировать случайным временем системы НЕ надо, потому что это делает метод не тестируемым.

2024-03-29 11:24 UTC, DimaTrushin commented on src/qs.cpp
> +        long_int h = gen();
Лучше не использовать генератор напрямую, дело в том, что он генерирует какую-то псевдопоследовательность, но ее характеристики implementation defined. И потому лучше использовать поверх генератора движки по генерации из нужного распределения. вроде uniform или normal или еще что.

2024-03-29 11:24 UTC, DimaTrushin commented on src/qs.cpp
> +                result.factors.push_back(std::move(factor.value()));
Тут одновременно 4 scope и нарушение уровня доступа.

2024-03-29 11:24 UTC, DimaTrushin commented on src/qs.cpp
> +        Fill(i, p, logs);
Этот fill совсем не говорит чем именно он заполняет.

2024-03-29 11:24 UTC, DimaTrushin commented on src/qs.cpp
> +std::optional<Factor> Sieve::IsDecomposed(Config & cf, size_t i, const long_int & n)
У тебя выходные параметры, то в начале списка аргументов, то в конце. Будь единообразным.

2024-03-29 11:24 UTC, DimaTrushin commented on src/rho_factorization.cpp
> +enum
1) НЕ пиши в global namespace
2) НЕ делай enum-ы внутри namespace, только внутри struct или class, потому что тогда эти имена утекают в глобальное пространство имен.
3) Лучше вообще не использовать enum, а использовать enum class. Если тебе нужны они как маски, то тогда помести его внутрь struct
```cpp
struct Mask {
  enum {
    DefCValue = 3,
    DefFreqValue = 10,
    ...
  };
};
```
Тогда ты можешь их как маски использовать в виде
```cpp
Mask::DefCValue | Mask::DefFreqValue
```
4) Не используй стиль CAPS_ONLY для чего-либо кроме макросов. Это путает людей!

2024-03-29 11:24 UTC, DimaTrushin commented on src/rho_factorization.cpp
> +    MAX_ATTEMP = 100,
Это совершенно не связанные друг с другом величины, которые вообще говоря еще и могут быть разного типа. Это больше похоже на структуру. Если тебе нужны константы внутри класса, то заведи static constexpr выражение нужного типа для каждой из константы. Или заведи struct с этими параметрами и передавай эту структуру как аргумент настроечный.

2024-03-29 11:24 UTC, DimaTrushin commented on src/rho_factorization.cpp
> +    frequency_ = DEF_FREQ_VALUE;
Что за питонячий стиль? Перенести все в список инициализации.

2024-03-29 11:24 UTC, DimaTrushin commented on src/rho_factorization.cpp
> +RhoFactorization::RhoFactorization(const long_int & c, const size_t & max, const size_t & frequency)
Не передавай встроенные типы по ссылке. Дело в том, что size_t сам имеет размер в один указатель и const size_t& имеет размер в один указатель. Потому ты передаешь ровно столько же данных в виде аргумента, но теперь тебе еще надо сделать один дополнительный jump в памяти по ссылке. Не надо этого делать. Встроенные типы всегда передаются by value.

2024-03-29 11:24 UTC, DimaTrushin commented on src/rho_factorization.cpp
> +Factor RhoFactorization::Factorize(long_int n, long_int x1)
Почему ты принимаешь аргументы не по константной ссылке?

2024-03-29 11:24 UTC, DimaTrushin commented on src/rho_factorization.cpp
> +    const std::array<long_int, 7> primes = {2, 3, 5, 7, 11, 13, 61631};
Вот это выглядит как магическая константа.

2024-03-29 11:24 UTC, DimaTrushin commented on src/rho_factorization.cpp
> +        std::cerr << "Warning: Value " << n << " is Pseudoprime\n";
Какого хуя ты пишешь в std::cerr? Что случилось с std::cout? Не пиши в cerr.

2024-03-29 11:24 UTC, DimaTrushin commented on src/rho_factorization.cpp
> +                    return g;
О, рекорд. 5 вложенных scope.

2024-03-29 11:24 UTC, DimaTrushin commented on tests/gaussian_test.cpp
> +        factors.push_back(std::move(BasicFactorization(primes[i] * primes[i + 1])));
Не нужный std::move. Любой временный объект уже rvalue, потому его не надо кастовать. Кроме того, тут ты этим кастом запрещаешь rvo, если аргумент принимается по значению.

2024-03-29 11:24 UTC, DimaTrushin commented on tests/qs_factor_test.cpp
> +// {
Не оставляй закомментированный код. Храни его в отдельных ветках либо в истории гита.

2024-03-29 11:24 UTC, DimaTrushin commented on tests/basic_test.cpp
> +long_int BasicPow(const long_int & a, long_int b)
Почему этой функции нет в basic.hpp?

2024-05-13 16:57 UTC, merged